resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/599d27a05597f96b9bfffa7920806fa638dcea10/snapshot.yaml
compiler: ghc-8.6.5


packages:
  - cardano-explorer-db
  - cardano-explorer-db/test
  - cardano-explorer-node
  - cardano-explorer
  - jormungandr-explorer-node

ghc-options:
  cardano-explorer-db:          -Wall -Werror -fwarn-redundant-constraints
  cardano-explorer-node:        -Wall -Werror -fwarn-redundant-constraints

extra-deps:
  - bech32-1.0.0@sha256:6bd23abe4a11d61a2d41fdb11db9e1361fc43c215cf2b8602cafaa516c8b6d76,2017
  - binary-0.8.7.0
  - bimap-0.4.0
  - brick-0.47.1
  - config-ini-0.2.4.0
  - containers-0.5.11.0
  - data-clist-0.1.2.3
  - ekg-prometheus-adapter-0.1.0.4
  - esqueleto-3.0.0
  - generic-monoid-0.1.0.0
  - libsystemd-journal-1.4.4
  - persistent-2.10.0
  - persistent-postgresql-2.10.0
  - persistent-template-2.7.2
  - prometheus-2.1.2
  - pvss-0.2.0
  - tasty-hedgehog-1.0.0.1
  - text-zipper-0.10.1
  - time-units-1.0.0
  - word-wrap-0.4.1
  - transformers-except-0.1.1
  - text-ansi-0.1.0

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 8abae427c44f0b447117f78e2c1f5006dac2edf8
    subdirs:
      - cardano-shell

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 599d27a05597f96b9bfffa7920806fa638dcea10
    subdirs:
      - .
      - test

  - ../cardano-wallet/lib/jormungandr
  - ../cardano-wallet/lib/cli
  - ../cardano-wallet/lib/core
  - ../cardano-wallet/lib/launcher
  - ../cardano-wallet/lib/text-class

  # - git: https://github.com/input-output-hk/cardano-wallet.git
  #   commit: 52eb3191604ea607ca04f287bc6efe6407a2241b
  #   subdirs:
  #     - lib/jormungandr
  #     - lib/cli
  #     - lib/core
  #     - lib/launcher
  #     - lib/text-class

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: ba6e4eaf61903d2bd4d745215bae29d35a58d0b6
    subdirs:
      - contra-tracer
      - iohk-monitoring
      - plugins/backend-aggregation
      - plugins/backend-editor
      - plugins/backend-ekg
      - plugins/backend-monitoring
      - plugins/scribe-systemd

  - git: https://github.com/input-output-hk/cardano-node
    commit: dc3af18f7fda2161b7e6619894beafc8462f5266
    subdirs:
      - cardano-config
      - cardano-node

  - git: https://github.com/input-output-hk/cardano-base
    commit: 5c575d46afbfe333de0ccba70b084db8302abf42
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 8854e56b68ab3b73ed2fd445d8c1db7d34b7c7f2
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/ouroboros-network
    commit: e3a2401aa324afe1287c89d827a92f2e784a3da0
    subdirs:
      - io-sim-classes
      - network-mux
      - ouroboros-network
      - ouroboros-consensus
      - typed-protocols
      - typed-protocols-cbor

nix:
  packages:
    - zlib
    - openssl
    - postgresql
    - pkg-config
    - systemd
    - sqlite
